### ISSUE TITLE
`SyntaxError: Unexpected token 'e', "export var"... is not valid JSON`

### ISSUE THREAD

**Issue by georgjaehnig** [vapier/rollup-plugin-git-info#1]
Having [done all the Install steps](https://github.com/trovu/trovu-web/compare/master...120-communicate-currently-deployed-version-to-user), I get
```
SyntaxError: Unexpected token 'e', "export var"... is not valid JSON
    at JSON.parse (<anonymous>)
    at Object.transform ([...]/node_modules/rollup-plugin-git-info/dist/rollup-plugin-git-info.cjs:157:25)
    at [...]/node_modules/rollup/dist/shared/rollup.js:18971:25
```
on calling `rollup --config --watch`

My context:

* Node v19.7.0
* "rollup": "^2.38.0"

Let me know if you need more info.

**Comment by georgjaehnig** [comment]
OK, I could solve it by myself: I had to remove `json()` from the `plugins` array in `rollup.config.js`.
